#!/bin/bash

# Prepare downloaded files for import into MariaDB / MySQL database weatherstations

DEBUG=OFF

# Color for output

red=$(tput setaf 1)
green=$(tput setaf 2)
blue=$(tput setaf 4)
reset=$(tput sgr0)

AWK="$(dirname $0)/awk"
DAT="$(dirname $0)/../data"
SED="$(dirname $0)/sed"
SQL="$(dirname $0)/../SQL"
TMP=$(mktemp -d)
TMP=/tmp/

if [ -n "$1" ]
then
    DEVICE=$1
else
    DEVICE=1
fi

rm "${TMP}/RoomLoggReports.csv" 2>/dev/null

for F in "${DAT}/${DEVICE}/"*"A.CSV"
do
    CSVFILE=$(basename "$F")
    CHAN=$(echo ${CSVFILE} | sed 's#.*CH##;s#A.CSV##')
    
    sed -f "${SED}/report.sed" "${DAT}/${DEVICE}/${CSVFILE}" \
    | sed 's#^#'${DEVICE}','${CHAN}',#;' \
    >> "${TMP}/RoomLoggReports.csv"

done
